### ISSUE TITLE
progress issue

### ISSUE THREAD

**Issue by renyijiu** [wnma3mz/Tools#2]
https://github.com/wnma3mz/Tools/blob/57da595b1bbe4e55aaff82323dc33d11ebec8160/daily_image/generate_image.py#L63

闰年是366天，这边直接写死不太好，另外，起始日期也是直接写的2018-01-01，后续这也是有问题的。两点小建议，望周知。

**Comment by wnma3mz** [comment]
已修改，多谢提醒
