### ISSUE TITLE
联通相关数据删除

### ISSUE THREAD

**Issue by syclh** [wnma3mz/Tools#3]
您好，我是联通智慧安全敏感信息监测处置组的，您在Github平台是上传的信息涉及到联通内部敏感数据，希望您这边能将相关信息下线删除，URL如下：
https://github.com/wnma3mz/Tools/blob/af5aae61777374ae4c8dca4f518ee1a71d661a7a/networks/whois/domains_1535445739/%E6%B1%9F%E8%A5%BF%E5%B8%88%E8%8C%83%E5%A4%A7%E5%AD%A6-58.17.39.184.txt

**Comment by wnma3mz** [comment]
抱歉，才看到信息，现已删除
